name: Lint
on:
  push:
    branches:
      - "*"
    paths:
    - '**/*.py'
  pull_request:
    paths:
    - '**/*.py'
  workflow_call:

permissions:
  contents: read

jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: actions/setup-python@5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.13"
      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev
      - name: Run linter
        run: |
          uv run ruff format --diff
          uv run ruff check
