name: Test
on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  golangci:
    name: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@5
        with:
          python-version: "3.12"
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          version: "0.8.13"
      - name: Install dependencies
        run: |
          uv sync --locked --all-extras --dev
      - name: Run tests
        run: |
          uv run pytest
